from src.robot.ShigaToyoChiba import tasks  # noqa
from src.robot.GuiBanVeToei import tasks  # noqa
from src.robot.KyushuOsaka import tasks  # noqa
from src.robot.Tochigi import tasks  # noqa
from src.robot.DrawingClassic import tasks  # noqa
from src.robot.SeikyuOnline import tasks  # noqa
from src.robot.Sakura import tasks  # noqa
from src.robot.SeikyuNgoaiHanwa import tasks  # noqa
from src.robot.OHDMITSUMORI import tasks  # noqa
from src.robot.Kaneka import tasks  # noqa
from src.robot.TamaNouhinsumi import tasks  # noqa
from src.robot.FuriwakeOsaka import tasks  # noqa
from src.robot.AndPadShuko import tasks  # noqa
from src.robot.GuiMailNoukiKakunin import tasks  # noqa
